server {
    listen 80;
    server_name localhost;

    location / {
        # This points to your custom directory
        root /var/www/app; 
        index index.html;
	try_files $uri $uri/ =404;
    }
}
